### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NicoHinderling** [lucasespinosa28/magiceden-ML#1]
When you do price prediction, how far out are you saying the outputted predicted prize will be? 7 days? 30 days? etc

**Comment by lucasespinosa28** [comment]
> When you do price prediction, how far out are you saying the outputted predicted prize will be? 7 days? 30 days? etc

the idea is to predict the value that an NFT that has not yet been sold, using the metadata the price sold and the date and time, it is possible to have an approximate idea of the value of an NFT, whether it is expensive or cheap

but I could train a model using forecasting algorithm, with that it would be possible to predict the price in the future

**Comment by NicoHinderling** [comment]
got it, thank you!
